name: build

on:
  push:
      paths-ignore:
        - '**/*.md'
        - '.gitignore'
        - '.dependabot/**'
  schedule:
    - cron: "0 10 * * 1" # every monday at 10am

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: test
        run: |
          cd tests
          pip install --upgrade pip pipenv
          pipenv sync --dev
          pipenv run test
          docker run -d --name=gogs robertbeal/gogs
          if [[ -z 'docker ps --filter="name=gogs" --filter="health=healthy" -q' ]]; then exit 1; fi

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: variables
        run: curl --silent https://api.github.com/repos/gogs/gogs/releases/latest | jq -r '.tag_name' > version

      - name: build dependencies
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: docker hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build
        run: |
          docker buildx build \
            --push \
            --tag robertbeal/gogs:latest \
            --tag robertbeal/gogs:$(cat version) \
            --build-arg=VERSION="$(cat version)" \
            --build-arg=COMMIT_ID="$GITHUB_SHA" \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 .