name: Build

on:
  push:
      paths-ignore:
        - '**/*.md'
        - '.gitignore'
        - '.dependabot/**'
  schedule:
    - cron: "0 10 * * 1" # every monday at 10am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: test
        run: |
          cd tests
          pip install --upgrade pip pipenv
          pipenv sync --dev
          pipenv run test
